[project]
name = "guardrails"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faiss-cpu>=1.14.3",
    "fastembed>=0.8.0",
    "langchain>=1.3.14",
    "langchain-community>=0.4.2",
    "langchain-core>=1.5.1",
    "langchain-openrouter>=0.2.7",
    "langchain-text-splitters>=1.1.2",
    "nemoguardrails>=0.23.0",
    "streamlit>=1.60.0",
]
